# Generated by Django 6.0.4 on 2026-05-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('celebrate', 'Celebrate'), ('insightful', 'Insightful'), ('funny', 'Funny')], default='like', max_length=20),
        ),
    ]
